# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bogdansavianu/University/Year3/Sem1/Graphic_Processing/Lab9

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bogdansavianu/University/Year3/Sem1/Graphic_Processing/Lab9

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bogdansavianu/University/Year3/Sem1/Graphic_Processing/Lab9/CMakeFiles /Users/bogdansavianu/University/Year3/Sem1/Graphic_Processing/Lab9//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bogdansavianu/University/Year3/Sem1/Graphic_Processing/Lab9/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Lab9

# Build rule for target.
Lab9: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab9
.PHONY : Lab9

# fast build rule for target.
Lab9/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/build
.PHONY : Lab9/fast

src/audio/AudioManager.o: src/audio/AudioManager.cpp.o
.PHONY : src/audio/AudioManager.o

# target to build an object file
src/audio/AudioManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/audio/AudioManager.cpp.o
.PHONY : src/audio/AudioManager.cpp.o

src/audio/AudioManager.i: src/audio/AudioManager.cpp.i
.PHONY : src/audio/AudioManager.i

# target to preprocess a source file
src/audio/AudioManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/audio/AudioManager.cpp.i
.PHONY : src/audio/AudioManager.cpp.i

src/audio/AudioManager.s: src/audio/AudioManager.cpp.s
.PHONY : src/audio/AudioManager.s

# target to generate assembly for a file
src/audio/AudioManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/audio/AudioManager.cpp.s
.PHONY : src/audio/AudioManager.cpp.s

src/camera/Camera.o: src/camera/Camera.cpp.o
.PHONY : src/camera/Camera.o

# target to build an object file
src/camera/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/camera/Camera.cpp.o
.PHONY : src/camera/Camera.cpp.o

src/camera/Camera.i: src/camera/Camera.cpp.i
.PHONY : src/camera/Camera.i

# target to preprocess a source file
src/camera/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/camera/Camera.cpp.i
.PHONY : src/camera/Camera.cpp.i

src/camera/Camera.s: src/camera/Camera.cpp.s
.PHONY : src/camera/Camera.s

# target to generate assembly for a file
src/camera/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/camera/Camera.cpp.s
.PHONY : src/camera/Camera.cpp.s

src/core/Engine.o: src/core/Engine.cpp.o
.PHONY : src/core/Engine.o

# target to build an object file
src/core/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/core/Engine.cpp.o
.PHONY : src/core/Engine.cpp.o

src/core/Engine.i: src/core/Engine.cpp.i
.PHONY : src/core/Engine.i

# target to preprocess a source file
src/core/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/core/Engine.cpp.i
.PHONY : src/core/Engine.cpp.i

src/core/Engine.s: src/core/Engine.cpp.s
.PHONY : src/core/Engine.s

# target to generate assembly for a file
src/core/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/core/Engine.cpp.s
.PHONY : src/core/Engine.cpp.s

src/entities/Pokemon.o: src/entities/Pokemon.cpp.o
.PHONY : src/entities/Pokemon.o

# target to build an object file
src/entities/Pokemon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/entities/Pokemon.cpp.o
.PHONY : src/entities/Pokemon.cpp.o

src/entities/Pokemon.i: src/entities/Pokemon.cpp.i
.PHONY : src/entities/Pokemon.i

# target to preprocess a source file
src/entities/Pokemon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/entities/Pokemon.cpp.i
.PHONY : src/entities/Pokemon.cpp.i

src/entities/Pokemon.s: src/entities/Pokemon.cpp.s
.PHONY : src/entities/Pokemon.s

# target to generate assembly for a file
src/entities/Pokemon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/entities/Pokemon.cpp.s
.PHONY : src/entities/Pokemon.cpp.s

src/graphics/effects/Rain.o: src/graphics/effects/Rain.cpp.o
.PHONY : src/graphics/effects/Rain.o

# target to build an object file
src/graphics/effects/Rain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/graphics/effects/Rain.cpp.o
.PHONY : src/graphics/effects/Rain.cpp.o

src/graphics/effects/Rain.i: src/graphics/effects/Rain.cpp.i
.PHONY : src/graphics/effects/Rain.i

# target to preprocess a source file
src/graphics/effects/Rain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/graphics/effects/Rain.cpp.i
.PHONY : src/graphics/effects/Rain.cpp.i

src/graphics/effects/Rain.s: src/graphics/effects/Rain.cpp.s
.PHONY : src/graphics/effects/Rain.s

# target to generate assembly for a file
src/graphics/effects/Rain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/graphics/effects/Rain.cpp.s
.PHONY : src/graphics/effects/Rain.cpp.s

src/graphics/models/Mesh.o: src/graphics/models/Mesh.cpp.o
.PHONY : src/graphics/models/Mesh.o

# target to build an object file
src/graphics/models/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/graphics/models/Mesh.cpp.o
.PHONY : src/graphics/models/Mesh.cpp.o

src/graphics/models/Mesh.i: src/graphics/models/Mesh.cpp.i
.PHONY : src/graphics/models/Mesh.i

# target to preprocess a source file
src/graphics/models/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/graphics/models/Mesh.cpp.i
.PHONY : src/graphics/models/Mesh.cpp.i

src/graphics/models/Mesh.s: src/graphics/models/Mesh.cpp.s
.PHONY : src/graphics/models/Mesh.s

# target to generate assembly for a file
src/graphics/models/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/graphics/models/Mesh.cpp.s
.PHONY : src/graphics/models/Mesh.cpp.s

src/graphics/models/Model3D.o: src/graphics/models/Model3D.cpp.o
.PHONY : src/graphics/models/Model3D.o

# target to build an object file
src/graphics/models/Model3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/graphics/models/Model3D.cpp.o
.PHONY : src/graphics/models/Model3D.cpp.o

src/graphics/models/Model3D.i: src/graphics/models/Model3D.cpp.i
.PHONY : src/graphics/models/Model3D.i

# target to preprocess a source file
src/graphics/models/Model3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/graphics/models/Model3D.cpp.i
.PHONY : src/graphics/models/Model3D.cpp.i

src/graphics/models/Model3D.s: src/graphics/models/Model3D.cpp.s
.PHONY : src/graphics/models/Model3D.s

# target to generate assembly for a file
src/graphics/models/Model3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/graphics/models/Model3D.cpp.s
.PHONY : src/graphics/models/Model3D.cpp.s

src/graphics/shaders/Shader.o: src/graphics/shaders/Shader.cpp.o
.PHONY : src/graphics/shaders/Shader.o

# target to build an object file
src/graphics/shaders/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/graphics/shaders/Shader.cpp.o
.PHONY : src/graphics/shaders/Shader.cpp.o

src/graphics/shaders/Shader.i: src/graphics/shaders/Shader.cpp.i
.PHONY : src/graphics/shaders/Shader.i

# target to preprocess a source file
src/graphics/shaders/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/graphics/shaders/Shader.cpp.i
.PHONY : src/graphics/shaders/Shader.cpp.i

src/graphics/shaders/Shader.s: src/graphics/shaders/Shader.cpp.s
.PHONY : src/graphics/shaders/Shader.s

# target to generate assembly for a file
src/graphics/shaders/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/graphics/shaders/Shader.cpp.s
.PHONY : src/graphics/shaders/Shader.cpp.s

src/input/Controls.o: src/input/Controls.cpp.o
.PHONY : src/input/Controls.o

# target to build an object file
src/input/Controls.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/input/Controls.cpp.o
.PHONY : src/input/Controls.cpp.o

src/input/Controls.i: src/input/Controls.cpp.i
.PHONY : src/input/Controls.i

# target to preprocess a source file
src/input/Controls.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/input/Controls.cpp.i
.PHONY : src/input/Controls.cpp.i

src/input/Controls.s: src/input/Controls.cpp.s
.PHONY : src/input/Controls.s

# target to generate assembly for a file
src/input/Controls.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/input/Controls.cpp.s
.PHONY : src/input/Controls.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/stb_image.o: src/utils/stb_image.cpp.o
.PHONY : src/utils/stb_image.o

# target to build an object file
src/utils/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/utils/stb_image.cpp.o
.PHONY : src/utils/stb_image.cpp.o

src/utils/stb_image.i: src/utils/stb_image.cpp.i
.PHONY : src/utils/stb_image.i

# target to preprocess a source file
src/utils/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/utils/stb_image.cpp.i
.PHONY : src/utils/stb_image.cpp.i

src/utils/stb_image.s: src/utils/stb_image.cpp.s
.PHONY : src/utils/stb_image.s

# target to generate assembly for a file
src/utils/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/utils/stb_image.cpp.s
.PHONY : src/utils/stb_image.cpp.s

src/utils/tiny_obj_loader.o: src/utils/tiny_obj_loader.cpp.o
.PHONY : src/utils/tiny_obj_loader.o

# target to build an object file
src/utils/tiny_obj_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/utils/tiny_obj_loader.cpp.o
.PHONY : src/utils/tiny_obj_loader.cpp.o

src/utils/tiny_obj_loader.i: src/utils/tiny_obj_loader.cpp.i
.PHONY : src/utils/tiny_obj_loader.i

# target to preprocess a source file
src/utils/tiny_obj_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/utils/tiny_obj_loader.cpp.i
.PHONY : src/utils/tiny_obj_loader.cpp.i

src/utils/tiny_obj_loader.s: src/utils/tiny_obj_loader.cpp.s
.PHONY : src/utils/tiny_obj_loader.s

# target to generate assembly for a file
src/utils/tiny_obj_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Lab9.dir/build.make CMakeFiles/Lab9.dir/src/utils/tiny_obj_loader.cpp.s
.PHONY : src/utils/tiny_obj_loader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Lab9"
	@echo "... src/audio/AudioManager.o"
	@echo "... src/audio/AudioManager.i"
	@echo "... src/audio/AudioManager.s"
	@echo "... src/camera/Camera.o"
	@echo "... src/camera/Camera.i"
	@echo "... src/camera/Camera.s"
	@echo "... src/core/Engine.o"
	@echo "... src/core/Engine.i"
	@echo "... src/core/Engine.s"
	@echo "... src/entities/Pokemon.o"
	@echo "... src/entities/Pokemon.i"
	@echo "... src/entities/Pokemon.s"
	@echo "... src/graphics/effects/Rain.o"
	@echo "... src/graphics/effects/Rain.i"
	@echo "... src/graphics/effects/Rain.s"
	@echo "... src/graphics/models/Mesh.o"
	@echo "... src/graphics/models/Mesh.i"
	@echo "... src/graphics/models/Mesh.s"
	@echo "... src/graphics/models/Model3D.o"
	@echo "... src/graphics/models/Model3D.i"
	@echo "... src/graphics/models/Model3D.s"
	@echo "... src/graphics/shaders/Shader.o"
	@echo "... src/graphics/shaders/Shader.i"
	@echo "... src/graphics/shaders/Shader.s"
	@echo "... src/input/Controls.o"
	@echo "... src/input/Controls.i"
	@echo "... src/input/Controls.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/stb_image.o"
	@echo "... src/utils/stb_image.i"
	@echo "... src/utils/stb_image.s"
	@echo "... src/utils/tiny_obj_loader.o"
	@echo "... src/utils/tiny_obj_loader.i"
	@echo "... src/utils/tiny_obj_loader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

